# -*- coding: utf-8 -*-
"""Boosting

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wT2yA8P86EyNLFz2Du2ZSfA7sRNYBR_P
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
df=pd.read_csv('heart.csv')
print(df.shape)
print(df.head())
x=df.drop('condition',axis=1)
y=df['condition']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
scaler=StandardScaler()
x_scaled=scaler.fit_transform(x_train)
xtests=scaler.transform(x_test)
basemodel=DecisionTreeClassifier(max_depth=1)
basemodel.fit(x_scaled,y_train)
base_accuracy=accuracy_score(y_test,basemodel.predict(xtests))
print("DecisionTree accuracy:",base_accuracy)

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
scaler=StandardScaler()
x_scaled=scaler.fit_transform(x_train)
xtests=scaler.transform(x_test)
basemodel=DecisionTreeClassifier(max_depth=1)
model=AdaBoostClassifier(estimator=basemodel,n_estimators=60)
model.fit(x_scaled,y_train)
y_predict=model.predict(xtests)
print("Adaboosting Accuracy:",accuracy_score(y_test,y_predict))

from sklearn.ensemble import GradientBoostingClassifier
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
scaler=StandardScaler()
x_scaled=scaler.fit_transform(x_train)
xtests=scaler.transform(x_test)
basemodel=DecisionTreeClassifier(max_depth=1)
model=GradientBoostingClassifier(n_estimators=70,learning_rate=0.5,max_depth=3)
model.fit(x_scaled,y_train)
y_predicts=model.predict(xtests)
print("Gradientboosting Accuracy:",accuracy_score(y_test,y_predicts))

from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
import pandas as pd
df=pd.read_csv('heart.csv')
x=df.drop('condition',axis=1)
y=df['condition']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
scaler=StandardScaler()
x_scaled=scaler.fit_transform(x_train)
xtests=scaler.transform(x_test)
model=XGBClassifier(n_estimators=2,learning_rate=0.1,max_depth=3)
model.fit(x_scaled,y_train)
pr=model.predict(xtests)
print("XGboost Accuracy:",accuracy_score(y_test,pr))

!pip install lightgbm
import lightgbm as lgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
import pandas as pd
df=pd.read_csv('heart.csv')
x=df.drop('condition',axis=1)
y=df['condition']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
scaler=StandardScaler()
x_scaled = scaler.fit_transform(x_train)
xtests = scaler.transform(x_test)
x_train_scaled_df = pd.DataFrame(x_scaled, columns=x_train.columns)
x_test_scaled_df = pd.DataFrame(xtests, columns=x_test.columns)
model=lgb.LGBMClassifier(n_estimators=60, learning_rate=0.1, max_depth=3, force_col_wise=True, verbose=-1)
model.fit(x_train_scaled_df,y_train)
prediction=model.predict(x_test_scaled_df)
print("LightGBM Accuracy:",accuracy_score(y_test,prediction))

model=lgb.LGBMClassifier(n_estimators=10, learning_rate=0.1, max_depth=3, force_col_wise=True, verbose=-1)
model.fit(x_train_scaled_df,y_train)
prediction=model.predict(x_test_scaled_df)
print("LightGBM Accuracy:",accuracy_score(y_test,prediction))

print("DecisionTree accuracy:",base_accuracy)
print("Adaboosting Accuracy:",accuracy_score(y_test,y_predict))
print("Gradientboosting Accuracy:",accuracy_score(y_test,y_predicts))
print("XGboost Accuracy:",accuracy_score(y_test,pr))
print("LightGBM Accuracy:",accuracy_score(y_test,prediction))